const CODES: Record<string, string> = {
  'algeria': 'dz',
  'argentina': 'ar',
  'australia': 'au',
  'austria': 'at',
  'belgium': 'be',
  'bolivia': 'bo',
  'bosnia-herzegovina': 'ba',
  'brazil': 'br',
  'cameroon': 'cm',
  'canada': 'ca',
  'cape verde': 'cv',
  'chile': 'cl',
  'colombia': 'co',
  'congo dr': 'cd',
  'costa rica': 'cr',
  'croatia': 'hr',
  'curacao': 'cw',
  'czechia': 'cz',
  'czech republic': 'cz',
  'denmark': 'dk',
  'ecuador': 'ec',
  'egypt': 'eg',
  'england': 'gb-eng',
  'france': 'fr',
  'germany': 'de',
  'ghana': 'gh',
  'greece': 'gr',
  'haiti': 'ht',
  'honduras': 'hn',
  'hungary': 'hu',
  'indonesia': 'id',
  'iran': 'ir',
  'iraq': 'iq',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  'jamaica': 'jm',
  'japan': 'jp',
  'jordan': 'jo',
  'kenya': 'ke',
  'mali': 'ml',
  'mexico': 'mx',
  'morocco': 'ma',
  'netherlands': 'nl',
  'new zealand': 'nz',
  'nigeria': 'ng',
  'north korea': 'kp',
  'norway': 'no',
  'panama': 'pa',
  'paraguay': 'py',
  'peru': 'pe',
  'poland': 'pl',
  'portugal': 'pt',
  'qatar': 'qa',
  'romania': 'ro',
  'saudi arabia': 'sa',
  'scotland': 'gb-sct',
  'senegal': 'sn',
  'serbia': 'rs',
  'slovakia': 'sk',
  'slovenia': 'si',
  'south africa': 'za',
  'south korea': 'kr',
  'korea republic': 'kr',
  'republic of korea': 'kr',
  'spain': 'es',
  'sweden': 'se',
  'switzerland': 'ch',
  'togo': 'tg',
  'tunisia': 'tn',
  'turkey': 'tr',
  'turkiye': 'tr',
  'ukraine': 'ua',
  'united states': 'us',
  'usa': 'us',
  'uruguay': 'uy',
  'uzbekistan': 'uz',
  'venezuela': 've',
  'wales': 'gb-wls',
}

function normalize(name: string): string {
  return name.toLowerCase().trim().normalize('NFD').replace(/[̀-ͯ]/g, '')
}

export function getFlagUrl(teamName: string): string {
  const code = CODES[normalize(teamName)] ?? CODES[teamName.toLowerCase().trim()] ?? ''
  return code ? `https://flagcdn.com/w40/${code}.png` : ''
}
